# This service account needs permissions to perform build actions (GKE, Docker, etc.)
serviceAccount: "547284571983-compute@developer.gserviceaccount.com"

# Store logs in the specified Cloud Storage bucket
logsBucket: "gs://transfer-proj"

steps:
  # Step 1: Authenticate with GKE and set cluster environment variables
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CLOUDSDK_COMPUTE_REGION=us-central1
        export CLOUDSDK_COMPUTE_ZONE=us-central1-a  # Replace with your GKE cluster's zone
        export CLOUDSDK_CONTAINER_CLUSTER=cluster-1  # Replace with your GKE cluster's name
        gcloud container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER --region=$CLOUDSDK_COMPUTE_REGION

  # Step 2: Pull Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA || exit 0

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
      - '-t'
      - 'gcr.io/black-beach-416616/project:latest'
      - '.'

  # Step 4: Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CLOUDSDK_COMPUTE_REGION=us-central1
        export CLOUDSDK_COMPUTE_ZONE=us-central1-a  # Replace with your GKE cluster's zone
        export CLOUDSDK_CONTAINER_CLUSTER=cluster-1  # Replace with your GKE cluster's name
        kubectl apply -f kubernetes-manifests/

  # Step 5: Set image for deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export CLOUDSDK_COMPUTE_REGION=us-central1
        export CLOUDSDK_COMPUTE_ZONE=us-central1-a  # Replace with your GKE cluster's zone
        export CLOUDSDK_CONTAINER_CLUSTER=cluster-1  # Replace with your GKE cluster's name
        kubectl set image deployment project project=gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA

# Push images to Google Container Registry with tags
images:
  - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
  - 'gcr.io/black-beach-416616/project:latest'
