# This service account needs permissions to perform build actions (GKE, Docker, etc.)
serviceAccount: "547284571983-compute@developer.gserviceaccount.com"

# Store logs in the specified Cloud Storage bucket
logsBucket: "gs://transfer-proj"

steps:
  # Step 1: Authenticate with GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-1 --region=us-central1


  # Step 2: Authenticate with GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-1 --region=us-central1

  # Step 3: Pull Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA || exit 0

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
      - '-t'
      - 'gcr.io/black-beach-416616/project:latest'
      - '.'

  # Step 5: Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes-manifests/'

  # Step 6: Set image for deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment'
      - 'project'
      - 'project=gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'

# Push images to Google Container Registry with tags
images:
  - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
  - 'gcr.io/black-beach-416616/project:latest'
