# This service account needs permissions to perform build actions (GKE, Docker, etc.)
serviceAccount: "547284571983-compute@developer.gserviceaccount.com"

# Store logs in the specified Cloud Storage bucket
logsBucket: "gs://transfer-proj"

steps:
  # Step 1: Create GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta container --project "black-beach-416616" clusters create "cluster-1" \
        --no-enable-basic-auth \
        --cluster-version "1.27.8-gke.1067004" \
        --release-channel "regular" \
        --machine-type "e2-small" \
        --image-type "COS_CONTAINERD" \
        --disk-type "pd-balanced" \
        --disk-size "10" \
        --metadata disable-legacy-endpoints=true \
        --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
        --num-nodes "2" \
        --logging=SYSTEM,WORKLOAD \
        --monitoring=SYSTEM \
        --enable-ip-alias \
        --network "projects/black-beach-416616/global/networks/default" \
        --subnetwork "projects/black-beach-416616/regions/us-central1/subnetworks/default" \
        --no-enable-intra-node-visibility \
        --default-max-pods-per-node "110" \
        --security-posture=standard \
        --workload-vulnerability-scanning=disabled \
        --no-enable-master-authorized-networks \
        --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver \
        --enable-autoupgrade \
        --enable-autorepair \
        --max-surge-upgrade 1 \
        --max-unavailable-upgrade 0 \
        --binauthz-evaluation-mode=DISABLED \
        --enable-managed-prometheus \
        --enable-shielded-nodes

  # Step 2: Authenticate with GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-1 --region=us-central1

  # Step 3: Pull Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA || exit 0

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
      - '-t'
      - 'gcr.io/black-beach-416616/project:latest'
      - '.'

  # Step 5: Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes-manifests/'

  # Step 6: Set image for deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment'
      - 'project'
      - 'project=gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'

# Push images to Google Container Registry with tags
images:
  - 'gcr.io/black-beach-416616/project:$BRANCH_NAME-$COMMIT_SHA'
  - 'gcr.io/black-beach-416616/project:latest'
