steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/black-beach-416616/project:$COMMIT_SHA', '.']
  # Step 2: Push Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/black-beach-416616/project:$COMMIT_SHA']
  # Step 3: Authenticate with GKE and apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes-manifests/']
    env:
      - 'CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True'
      - 'KUBECONFIG=/builder/home/.kube/config'
timeout: '1600s'
